show processlist

SELECT CONCAT('KILL ', id, ';') 
FROM information_schema.processlist 
WHERE user = 'hkcode';

CREATE TABLE T1_김효관 AS
SELECT * 
FROM T1

SELECT * 
FROM T1_김효관

WHERE 위치 = '잠실'

INSERT INTO T1_김효관 (아이디, 도시개발사)
VALUES ('A05','스금팀');

SELECT *
FROM NGROK_TEST



UPDATE T1_김효관
SET 도시개발사 = '진아팀NEW'
WHERE 아이디 = 'A03'


-- 0(리눅스, 대소문자 구별) 1-2 (구별안함)
SHOW VARIABLES LIKE 'lower_case_table_names';


-- 대소문자를 구별한다 (기본 리눅스는)
SELECT * 
FROM ACCOUNT

CREATE TABLE KOPO_PRODUCT_VOLUME_HKCODE(
	REGIONID VARCHAR(20),
	PRODUCTGROUP VARCHAR(20),
	YEARWEEK VARCHAR(10),
	QTY DOUBLE
);

-- 테이블 삭제
DROP TABLE KOPO_PRODUCT_VOLUME_HKCODE;

-- 테이블 재생성
CREATE TABLE KOPO_PRODUCT_VOLUME_HKCODE(
	REGIONID VARCHAR(20),
	PRODUCTGROUP VARCHAR(20),
	YEARWEEK VARCHAR(10),
	QTY DOUBLE
)

SHOW TABLES

SELECT  *
FROM TABS


CREATE TABLE HKCODE_T1(
	REGIONID VARCHAR(100),
	QTY DOUBLE
)


SELECT '실적정보' AS MEASURE_NAME,
	A.REGIONID AS SALESID,
	A.PRODUCTGROUP,
	A.YEARWEEK,
	A.QTY,
	NOW() AS BATCH_TIME
FROM KOPO_PRODUCT_VOLUME_HKCODE A

SELECT *
FROM KOPO_PRODUCT_VOLUME_HKCODE






-- 데이터 생성 (기본)
INSERT INTO KOPO_PRODUCT_VOLUME_HKCODE
VALUES ('서울','한국은행','202401',1000),
       ('서울','한국은행','202402',2000),
       ('서울','한국은행','202403',3000);

-- 데이터 생성 (특정컬럼)
INSERT INTO KOPO_PRODUCT_VOLUME_HKCODE
(REGIONID, PRODUCTGROUP, YEARWEEK)
VALUES ('서울','한국은행','202401')

-- 데이터 수정
UPDATE KOPO_PRODUCT_VOLUME_HKCODE
SET YEARWEEK = '202402'
WHERE QTY IS NULL

-- 데이터 수정
UPDATE KOPO_PRODUCT_VOLUME_HKCODE
SET QTY = 1500
WHERE YEARWEEK = '202402'

-- 데이터 삭제
DELETE FROM KOPO_PRODUCT_VOLUME_HKCODE
WHERE YEARWEEK = '202402'


SELECT DISTINCT REGIONID
FROM KOPO_CHANNEL_SEASONALITY_NEW


-- KOPO_PRODUCT_VOLUME2 테이블에서
-- ST0002 상품이면서 
-- 202415, 202416년도 제품만 조회하세요


SELECT *
FROM KOPO_PRODUCT_VOLUME2
WHERE PRODUCTGROUP = 'ST0002'
AND (YEARWEEK = '201415'
OR YEARWEEK = '201416')

SELECT *
FROM KOPO_PRODUCT_VOLUME2
WHERE PRODUCTGROUP = 'ST0002'
AND YEARWEEK IN ( '201415', '201416')


SELECT A.*,
	   ROUND(A.VOLUME * 1.23,0) AS VOLUME_UP
FROM KOPO_PRODUCT_VOLUME2 A

SELECT A.*,
	ROUND( A.PMAP - (A.PMAP * 0.1),0) AS PMAP2
FROM KOPO_PROMOTION A

SELECT A.*,
	   ROUND( IR / MAP_PRICE, 2) AS PROMOTION_RATIO
FROM KOPO_PROMOTION A


SELECT 6/NULL
FROM DUAL

SELECT * 
FROM KOPO_PROMOTION
WHERE ITEM IN ('ITEM04013','ITEM011124')

SELECT * 
FROM KOPO_PROMOTION
WHERE NOT ITEM IN (SELECT DISTINCT ITEM
			   FROM KOPO_RECALL_ITEM)
		
SELECT * 
FROM KOPO_PROMOTION	
WHERE ITEM LIKE '%04%'
			   
SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'analdb2'
AND TABLE_NAME LIKE 'kopo_%'

SELECT *
FROM KOPO_PROMOTION 
WHERE REGIONID NOT IN ('A01')


SELECT *
FROM KOPO_PROMOTION 
WHERE REGIONID IS NOT NULL

SELECT *
FROM GPT_ORDERS

SELECT *
FROM KOPO_CHANNEL_RESULT

WHERE 

SELECT go.*
FROM gpt_orders go
WHERE go.id IN (
        SELECT DISTINCT gc.id
        FROM gpt_customers gc
        WHERE city IN ('Seoul','Busan')
) 


-- 집중력
SELECT *
FROM GPT_ORDERS 
WHERE CUSTOMER_ID IN (SELECT ID
					  FROM GPT_CUSTOMERS 
					  WHERE CITY IN ('Seoul', 'Busan')
)



SELECT * 
FROM KOPO_PROMOTION

INSERT INTO KOPO_PROMOTION (REGIONID) VALUES ('')






WHERE REGIONID IS NULL
			   
			   

SELECT *
FROM KOPO_RECALL_ITEM


SELECT 6/2
FROM DUAL



WHERE PLANWEEK < TARGETWEEK

