-- 0(리눅스, 대소문자 구별) 1-2 (구별안함)
SHOW VARIABLES LIKE 'lower_case_table_names';


-- 대소문자를 구별한다 (기본 리눅스는)
SELECT * 
FROM ACCOUNT

CREATE TABLE KOPO_PRODUCT_VOLUME_HKCODE(
	REGIONID VARCHAR(20),
	PRODUCTGROUP VARCHAR(20),
	YEARWEEK VARCHAR(10),
	QTY DOUBLE
);

-- 테이블 삭제
DROP TABLE KOPO_PRODUCT_VOLUME_HKCODE;

-- 테이블 재생성
CREATE TABLE KOPO_PRODUCT_VOLUME_HKCODE(
	REGIONID VARCHAR(20),
	PRODUCTGROUP VARCHAR(20),
	YEARWEEK VARCHAR(10),
	QTY DOUBLE
)

-- 데이터 생성 (기본)
INSERT INTO KOPO_PRODUCT_VOLUME_HKCODE
VALUES ('서울','한국은행','202401',1000),
       ('서울','한국은행','202402',2000),
       ('서울','한국은행','202403',3000);

-- 데이터 생성 (특정컬럼)
INSERT INTO KOPO_PRODUCT_VOLUME_HKCODE
(REGIONID, PRODUCTGROUP, YEARWEEK)
VALUES ('서울','한국은행','202401')

-- 데이터 수정
UPDATE KOPO_PRODUCT_VOLUME_HKCODE
SET YEARWEEK = '202402'
WHERE QTY IS NULL

-- 데이터 수정
UPDATE KOPO_PRODUCT_VOLUME_HKCODE
SET QTY = 1500
WHERE YEARWEEK = '202402'

-- 데이터 삭제
DELETE FROM KOPO_PRODUCT_VOLUME_HKCODE
WHERE YEARWEEK = '202402'

